[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version="0.5.1"}
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
