name: Publish Docker Image

on:
  push:
    branches:
      - main  # "nightly" wird bei jedem Push auf main gebaut
  release:
    types:
      - published  # "latest" wird nur bei einem neuen Release gebaut

  workflow_dispatch:  # Manuelles Triggern erlaubt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Image Tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=nightly" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/inventarwerk:${{ env.tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventarwerk:${{ env.tag }}
