name: Check lint

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
      
      - uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Install and Lint 🎨
        working-directory: frontend
        run: |
          npm install
          npm run lint:check